// This file is generated with "update_icon_font.py" from FontAwesome's metadata.

// List of method calls for IconSelectDialog.
addIcon(0xf26e, QStringList() << "500px");
addIcon(0xf368, QStringList() << "accessible icon" << "accessibility" << "wheelchair" << "handicap" << "person" << "wheelchair-alt");
addIcon(0xf369, QStringList() << "accusoft");
addIcon(0xf2b9, QStringList() << "address book");
addIcon(0xf2bb, QStringList() << "address card");
addIcon(0xf042, QStringList() << "adjust" << "contrast");
addIcon(0xf170, QStringList() << "app.net");
addIcon(0xf36a, QStringList() << "adversal");
addIcon(0xf36b, QStringList() << "affiliatetheme");
addIcon(0xf36c, QStringList() << "algolia");
addIcon(0xf037, QStringList() << "align-center" << "middle" << "text");
addIcon(0xf039, QStringList() << "align-justify" << "text");
addIcon(0xf036, QStringList() << "align-left" << "text");
addIcon(0xf038, QStringList() << "align-right" << "text");
addIcon(0xf270, QStringList() << "amazon");
addIcon(0xf42c, QStringList() << "amazon pay");
addIcon(0xf0f9, QStringList() << "ambulance" << "vehicle" << "support" << "help");
addIcon(0xf2a3, QStringList() << "american sign language interpreting");
addIcon(0xf36d, QStringList() << "amilia");
addIcon(0xf13d, QStringList() << "anchor" << "link");
addIcon(0xf17b, QStringList() << "android" << "robot");
addIcon(0xf209, QStringList() << "angellist");
addIcon(0xf103, QStringList() << "angle double down" << "arrows");
addIcon(0xf100, QStringList() << "angle double left" << "laquo" << "quote" << "previous" << "back" << "arrows");
addIcon(0xf101, QStringList() << "angle double right" << "raquo" << "quote" << "next" << "forward" << "arrows");
addIcon(0xf102, QStringList() << "angle double up" << "arrows");
addIcon(0xf107, QStringList() << "angle-down" << "arrow");
addIcon(0xf104, QStringList() << "angle-left" << "previous" << "back" << "arrow");
addIcon(0xf105, QStringList() << "angle-right" << "next" << "forward" << "arrow");
addIcon(0xf106, QStringList() << "angle-up" << "arrow");
addIcon(0xf36e, QStringList() << "angry creative");
addIcon(0xf420, QStringList() << "angular");
addIcon(0xf36f, QStringList() << "app store");
addIcon(0xf370, QStringList() << "ios app store");
addIcon(0xf371, QStringList() << "apper systems ab");
addIcon(0xf179, QStringList() << "apple" << "osx" << "food");
addIcon(0xf415, QStringList() << "apple pay");
addIcon(0xf187, QStringList() << "archive" << "box" << "storage");
addIcon(0xf358, QStringList() << "alternate arrow circle down" << "download" << "arrow-circle-o-down");
addIcon(0xf359, QStringList() << "alternate arrow circle left" << "previous" << "back" << "arrow-circle-o-left");
addIcon(0xf35a, QStringList() << "alternate arrow circle right" << "next" << "forward" << "arrow-circle-o-right");
addIcon(0xf35b, QStringList() << "alternate arrow circle up" << "arrow-circle-o-up");
addIcon(0xf0ab, QStringList() << "arrow circle down" << "download");
addIcon(0xf0a8, QStringList() << "arrow circle left" << "previous" << "back");
addIcon(0xf0a9, QStringList() << "arrow circle right" << "next" << "forward");
addIcon(0xf0aa, QStringList() << "arrow circle up");
addIcon(0xf063, QStringList() << "arrow-down" << "download");
addIcon(0xf060, QStringList() << "arrow-left" << "previous" << "back");
addIcon(0xf061, QStringList() << "arrow-right" << "next" << "forward");
addIcon(0xf062, QStringList() << "arrow-up");
addIcon(0xf0b2, QStringList() << "alternate arrows" << "expand" << "enlarge" << "fullscreen" << "bigger" << "move" << "reorder" << "resize" << "arrow" << "arrows");
addIcon(0xf337, QStringList() << "alternate arrows horizontal" << "resize" << "arrows-h");
addIcon(0xf338, QStringList() << "alternate arrows vertical" << "resize" << "arrows-v");
addIcon(0xf2a2, QStringList() << "assistive listening systems");
addIcon(0xf069, QStringList() << "asterisk" << "details");
addIcon(0xf372, QStringList() << "asymmetrik, ltd.");
addIcon(0xf1fa, QStringList() << "at" << "email" << "e-mail");
addIcon(0xf373, QStringList() << "audible");
addIcon(0xf29e, QStringList() << "audio description");
addIcon(0xf41c, QStringList() << "autoprefixer");
addIcon(0xf374, QStringList() << "avianex");
addIcon(0xf421, QStringList() << "aviato");
addIcon(0xf375, QStringList() << "amazon web services (aws)");
addIcon(0xf04a, QStringList() << "backward" << "rewind" << "previous");
addIcon(0xf24e, QStringList() << "balance scale");
addIcon(0xf05e, QStringList() << "ban" << "delete" << "remove" << "trash" << "hide" << "block" << "stop" << "abort" << "cancel");
addIcon(0xf2d5, QStringList() << "bandcamp");
addIcon(0xf02a, QStringList() << "barcode" << "scan");
addIcon(0xf0c9, QStringList() << "bars" << "menu" << "drag" << "reorder" << "settings" << "list" << "ul" << "ol" << "checklist" << "todo" << "list" << "hamburger");
addIcon(0xf2cd, QStringList() << "bath");
addIcon(0xf244, QStringList() << "battery empty" << "power");
addIcon(0xf240, QStringList() << "battery full" << "power");
addIcon(0xf242, QStringList() << "battery 1/2 full" << "power");
addIcon(0xf243, QStringList() << "battery 1/4 full" << "power");
addIcon(0xf241, QStringList() << "battery 3/4 full" << "power");
addIcon(0xf236, QStringList() << "bed" << "travel");
addIcon(0xf0fc, QStringList() << "beer" << "alcohol" << "stein" << "drink" << "mug" << "bar" << "liquor");
addIcon(0xf1b4, QStringList() << "behance");
addIcon(0xf1b5, QStringList() << "behance square");
addIcon(0xf0f3, QStringList() << "bell" << "alert" << "reminder" << "notification");
addIcon(0xf1f6, QStringList() << "bell slash");
addIcon(0xf206, QStringList() << "bicycle" << "vehicle" << "bike");
addIcon(0xf378, QStringList() << "bimobject");
addIcon(0xf1e5, QStringList() << "binoculars");
addIcon(0xf1fd, QStringList() << "birthday cake");
addIcon(0xf171, QStringList() << "bitbucket" << "git" << "bitbucket-square");
addIcon(0xf379, QStringList() << "bitcoin");
addIcon(0xf37a, QStringList() << "bity");
addIcon(0xf27e, QStringList() << "font awesome black tie");
addIcon(0xf37b, QStringList() << "blackberry");
addIcon(0xf29d, QStringList() << "blind");
addIcon(0xf37c, QStringList() << "blogger");
addIcon(0xf37d, QStringList() << "blogger b");
addIcon(0xf293, QStringList() << "bluetooth");
addIcon(0xf294, QStringList() << "bluetooth");
addIcon(0xf032, QStringList() << "bold");
addIcon(0xf0e7, QStringList() << "lightning bolt" << "lightning" << "weather");
addIcon(0xf1e2, QStringList() << "bomb");
addIcon(0xf02d, QStringList() << "book" << "read" << "documentation");
addIcon(0xf02e, QStringList() << "bookmark" << "save");
addIcon(0xf2a1, QStringList() << "braille");
addIcon(0xf0b1, QStringList() << "briefcase" << "work" << "business" << "office" << "luggage" << "bag");
addIcon(0xf15a, QStringList() << "btc");
addIcon(0xf188, QStringList() << "bug" << "report" << "insect");
addIcon(0xf1ad, QStringList() << "building" << "work" << "business" << "apartment" << "office" << "company");
addIcon(0xf0a1, QStringList() << "bullhorn" << "announcement" << "share" << "broadcast" << "louder" << "megaphone");
addIcon(0xf140, QStringList() << "bullseye" << "target");
addIcon(0xf37f, QStringList() << "b\u00fcrom\u00f6bel-experte gmbh & co. kg.");
addIcon(0xf207, QStringList() << "bus" << "vehicle");
addIcon(0xf20d, QStringList() << "buysellads");
addIcon(0xf1ec, QStringList() << "calculator");
addIcon(0xf133, QStringList() << "calendar" << "date" << "time" << "when" << "event" << "calendar-o");
addIcon(0xf073, QStringList() << "alternate calendar" << "date" << "time" << "when" << "event" << "calendar");
addIcon(0xf274, QStringList() << "calendar check" << "ok");
addIcon(0xf272, QStringList() << "calendar minus");
addIcon(0xf271, QStringList() << "calendar plus");
addIcon(0xf273, QStringList() << "calendar times");
addIcon(0xf030, QStringList() << "camera" << "photo" << "picture" << "record");
addIcon(0xf083, QStringList() << "retro camera" << "photo" << "picture" << "record");
addIcon(0xf1b9, QStringList() << "car" << "vehicle");
addIcon(0xf0d7, QStringList() << "caret down" << "more" << "dropdown" << "menu" << "triangle down" << "arrow");
addIcon(0xf0d9, QStringList() << "caret left" << "previous" << "back" << "triangle left" << "arrow");
addIcon(0xf0da, QStringList() << "caret right" << "next" << "forward" << "triangle right" << "arrow");
addIcon(0xf150, QStringList() << "caret square down" << "more" << "dropdown" << "menu" << "caret-square-o-down");
addIcon(0xf191, QStringList() << "caret square left" << "previous" << "back" << "caret-square-o-left");
addIcon(0xf152, QStringList() << "caret square right" << "next" << "forward" << "caret-square-o-right");
addIcon(0xf151, QStringList() << "caret square up" << "caret-square-o-up");
addIcon(0xf0d8, QStringList() << "caret up" << "triangle up" << "arrow");
addIcon(0xf218, QStringList() << "shopping cart arrow down" << "shopping");
addIcon(0xf217, QStringList() << "add to shopping cart" << "add" << "shopping");
addIcon(0xf42d, QStringList() << "amazon pay credit card");
addIcon(0xf1f3, QStringList() << "american express credit card" << "amex");
addIcon(0xf416, QStringList() << "apple pay credit card");
addIcon(0xf24c, QStringList() << "diner's club credit card");
addIcon(0xf1f2, QStringList() << "discover credit card");
addIcon(0xf24b, QStringList() << "jcb credit card");
addIcon(0xf1f1, QStringList() << "mastercard credit card");
addIcon(0xf1f4, QStringList() << "paypal credit card");
addIcon(0xf1f5, QStringList() << "stripe credit card");
addIcon(0xf1f0, QStringList() << "visa credit card");
addIcon(0xf380, QStringList() << "centercode");
addIcon(0xf0a3, QStringList() << "certificate" << "badge" << "star");
addIcon(0xf1fe, QStringList() << "area chart" << "graph" << "analytics" << "area-chart");
addIcon(0xf080, QStringList() << "bar chart" << "graph" << "analytics" << "bar-chart");
addIcon(0xf201, QStringList() << "line chart" << "graph" << "analytics" << "line-chart");
addIcon(0xf200, QStringList() << "pie chart" << "graph" << "analytics" << "pie-chart");
addIcon(0xf00c, QStringList() << "check" << "checkmark" << "done" << "todo" << "agree" << "accept" << "confirm" << "tick" << "ok");
addIcon(0xf058, QStringList() << "check circle" << "todo" << "done" << "agree" << "accept" << "confirm" << "ok");
addIcon(0xf14a, QStringList() << "check square" << "checkmark" << "done" << "todo" << "agree" << "accept" << "confirm" << "ok");
addIcon(0xf13a, QStringList() << "chevron circle down" << "more" << "dropdown" << "menu" << "arrow");
addIcon(0xf137, QStringList() << "chevron circle left" << "previous" << "back" << "arrow");
addIcon(0xf138, QStringList() << "chevron circle right" << "next" << "forward" << "arrow");
addIcon(0xf139, QStringList() << "chevron circle up" << "arrow");
addIcon(0xf078, QStringList() << "chevron-down");
addIcon(0xf053, QStringList() << "chevron-left" << "bracket" << "previous" << "back");
addIcon(0xf054, QStringList() << "chevron-right" << "bracket" << "next" << "forward");
addIcon(0xf077, QStringList() << "chevron-up");
addIcon(0xf1ae, QStringList() << "child");
addIcon(0xf268, QStringList() << "chrome" << "browser");
addIcon(0xf111, QStringList() << "circle" << "dot" << "notification" << "circle-thin");
addIcon(0xf1ce, QStringList() << "circle notched" << "circle-o-notch");
addIcon(0xf328, QStringList() << "clipboard" << "paste");
addIcon(0xf017, QStringList() << "clock" << "watch" << "timer" << "late" << "timestamp" << "date");
addIcon(0xf24d, QStringList() << "clone" << "copy");
addIcon(0xf20a, QStringList() << "closed captioning" << "cc");
addIcon(0xf0c2, QStringList() << "cloud" << "save");
addIcon(0xf381, QStringList() << "cloud download-alt" << "cloud-download");
addIcon(0xf382, QStringList() << "cloud upload-alt" << "cloud-upload");
addIcon(0xf383, QStringList() << "cloudscale.ch");
addIcon(0xf384, QStringList() << "cloudsmith");
addIcon(0xf385, QStringList() << "cloudversify");
addIcon(0xf121, QStringList() << "code" << "html" << "brackets");
addIcon(0xf126, QStringList() << "code branch" << "git" << "fork" << "vcs" << "svn" << "github" << "rebase" << "version" << "branch" << "code-fork");
addIcon(0xf1cb, QStringList() << "codepen");
addIcon(0xf284, QStringList() << "codie pie");
addIcon(0xf0f4, QStringList() << "coffee" << "morning" << "mug" << "breakfast" << "tea" << "drink" << "cafe");
addIcon(0xf013, QStringList() << "cog" << "settings");
addIcon(0xf085, QStringList() << "cogs" << "settings");
addIcon(0xf0db, QStringList() << "columns" << "split" << "panes");
addIcon(0xf075, QStringList() << "comment" << "speech" << "notification" << "note" << "chat" << "bubble" << "feedback" << "message" << "texting" << "sms" << "conversation");
addIcon(0xf27a, QStringList() << "alternate comment" << "speech" << "notification" << "note" << "chat" << "bubble" << "feedback" << "message" << "texting" << "sms" << "conversation" << "commenting" << "commenting");
addIcon(0xf086, QStringList() << "comments" << "speech" << "notification" << "note" << "chat" << "bubble" << "feedback" << "message" << "texting" << "sms" << "conversation");
addIcon(0xf14e, QStringList() << "compass" << "safari" << "directory" << "menu" << "location");
addIcon(0xf066, QStringList() << "compress" << "collapse" << "combine" << "contract" << "merge" << "smaller");
addIcon(0xf20e, QStringList() << "connect develop");
addIcon(0xf26d, QStringList() << "contao");
addIcon(0xf0c5, QStringList() << "copy" << "duplicate" << "clone" << "file" << "files-o");
addIcon(0xf1f9, QStringList() << "copyright");
addIcon(0xf388, QStringList() << "cpanel");
addIcon(0xf25e, QStringList() << "creative commons");
addIcon(0xf09d, QStringList() << "credit card" << "money" << "buy" << "debit" << "checkout" << "purchase" << "payment" << "credit-card-alt");
addIcon(0xf125, QStringList() << "crop");
addIcon(0xf05b, QStringList() << "crosshairs" << "picker");
addIcon(0xf13c, QStringList() << "css 3 logo" << "code");
addIcon(0xf38b, QStringList() << "alternate css3 logo");
addIcon(0xf1b2, QStringList() << "cube");
addIcon(0xf1b3, QStringList() << "cubes");
addIcon(0xf0c4, QStringList() << "cut" << "scissors" << "scissors");
addIcon(0xf38c, QStringList() << "cuttlefish");
addIcon(0xf38d, QStringList() << "dungeons & dragons");
addIcon(0xf210, QStringList() << "dashcube");
addIcon(0xf1c0, QStringList() << "database");
addIcon(0xf2a4, QStringList() << "deaf");
addIcon(0xf1a5, QStringList() << "delicious logo");
addIcon(0xf38e, QStringList() << "deploy.dog");
addIcon(0xf38f, QStringList() << "deskpro");
addIcon(0xf108, QStringList() << "desktop" << "monitor" << "screen" << "desktop" << "computer" << "demo" << "device");
addIcon(0xf1bd, QStringList() << "deviantart");
addIcon(0xf1a6, QStringList() << "digg logo");
addIcon(0xf391, QStringList() << "digital ocean");
addIcon(0xf392, QStringList() << "discord");
addIcon(0xf393, QStringList() << "discourse");
addIcon(0xf394, QStringList() << "dochub");
addIcon(0xf395, QStringList() << "docker");
addIcon(0xf155, QStringList() << "dollar sign" << "usd" << "usd");
addIcon(0xf192, QStringList() << "dot circle" << "target" << "bullseye" << "notification");
addIcon(0xf019, QStringList() << "download" << "import");
addIcon(0xf396, QStringList() << "draft2digital");
addIcon(0xf17d, QStringList() << "dribbble");
addIcon(0xf397, QStringList() << "dribbble square");
addIcon(0xf16b, QStringList() << "dropbox");
addIcon(0xf1a9, QStringList() << "drupal logo");
addIcon(0xf399, QStringList() << "dyalog");
addIcon(0xf39a, QStringList() << "earlybirds");
addIcon(0xf282, QStringList() << "edge browser" << "browser" << "ie");
addIcon(0xf044, QStringList() << "edit" << "write" << "edit" << "update" << "pencil" << "pen");
addIcon(0xf052, QStringList() << "eject");
addIcon(0xf141, QStringList() << "horizontal ellipsis" << "dots");
addIcon(0xf142, QStringList() << "vertical ellipsis" << "dots");
addIcon(0xf423, QStringList() << "ember");
addIcon(0xf1d1, QStringList() << "galactic empire");
addIcon(0xf0e0, QStringList() << "envelope" << "email" << "e-mail" << "letter" << "support" << "mail" << "message" << "notification");
addIcon(0xf2b6, QStringList() << "envelope open" << "email" << "e-mail" << "letter" << "support" << "mail" << "message" << "notification");
addIcon(0xf199, QStringList() << "envelope square" << "email" << "e-mail" << "letter" << "support" << "mail" << "message" << "notification");
addIcon(0xf299, QStringList() << "envira gallery" << "leaf");
addIcon(0xf12d, QStringList() << "eraser" << "remove" << "delete");
addIcon(0xf39d, QStringList() << "erlang");
addIcon(0xf42e, QStringList() << "ethereum");
addIcon(0xf2d7, QStringList() << "etsy");
addIcon(0xf153, QStringList() << "euro sign" << "eur" << "eur");
addIcon(0xf362, QStringList() << "alternate exchange" << "transfer" << "arrows" << "arrow" << "exchange");
addIcon(0xf12a, QStringList() << "exclamation" << "warning" << "error" << "problem" << "notification" << "notify" << "alert");
addIcon(0xf06a, QStringList() << "exclamation circle" << "warning" << "error" << "problem" << "notification" << "notify" << "alert");
addIcon(0xf071, QStringList() << "exclamation triangle" << "warning" << "error" << "problem" << "notification" << "notify" << "alert");
addIcon(0xf065, QStringList() << "expand" << "enlarge" << "bigger" << "resize");
addIcon(0xf31e, QStringList() << "alternate expand arrows" << "enlarge" << "bigger" << "resize" << "move" << "arrows-alt");
addIcon(0xf23e, QStringList() << "expeditedssl");
addIcon(0xf35d, QStringList() << "alternate external link" << "open" << "new" << "external-link");
addIcon(0xf360, QStringList() << "alternate external link square" << "open" << "new" << "external-link-square");
addIcon(0xf06e, QStringList() << "eye" << "show" << "visible" << "views");
addIcon(0xf1fb, QStringList() << "eye dropper" << "eyedropper");
addIcon(0xf070, QStringList() << "eye slash" << "toggle" << "show" << "hide" << "visible" << "visiblity" << "views");
addIcon(0xf09a, QStringList() << "facebook" << "social network" << "facebook-official");
addIcon(0xf39e, QStringList() << "facebook f" << "facebook");
addIcon(0xf39f, QStringList() << "facebook messenger");
addIcon(0xf082, QStringList() << "facebook square" << "social network");
addIcon(0xf049, QStringList() << "fast-backward" << "rewind" << "previous" << "beginning" << "start" << "first");
addIcon(0xf050, QStringList() << "fast-forward" << "next" << "end" << "last");
addIcon(0xf1ac, QStringList() << "fax");
addIcon(0xf182, QStringList() << "female" << "woman" << "user" << "person" << "profile");
addIcon(0xf0fb, QStringList() << "fighter-jet" << "fly" << "plane" << "airplane" << "quick" << "fast" << "travel");
addIcon(0xf15b, QStringList() << "file" << "new" << "page" << "pdf" << "document");
addIcon(0xf15c, QStringList() << "alternate file" << "new" << "page" << "pdf" << "document" << "file-text");
addIcon(0xf1c6, QStringList() << "archive file");
addIcon(0xf1c7, QStringList() << "audio file");
addIcon(0xf1c9, QStringList() << "code file");
addIcon(0xf1c3, QStringList() << "excel file");
addIcon(0xf1c5, QStringList() << "image file");
addIcon(0xf1c1, QStringList() << "pdf file");
addIcon(0xf1c4, QStringList() << "powerpoint file");
addIcon(0xf1c8, QStringList() << "video file");
addIcon(0xf1c2, QStringList() << "word file");
addIcon(0xf008, QStringList() << "film" << "movie");
addIcon(0xf0b0, QStringList() << "filter" << "funnel" << "options");
addIcon(0xf06d, QStringList() << "fire" << "flame" << "hot" << "popular");
addIcon(0xf134, QStringList() << "fire-extinguisher");
addIcon(0xf269, QStringList() << "firefox" << "browser");
addIcon(0xf2b0, QStringList() << "first order");
addIcon(0xf3a1, QStringList() << "firstdraft");
addIcon(0xf024, QStringList() << "flag" << "report" << "notification" << "notify");
addIcon(0xf11e, QStringList() << "flag-checkered" << "report" << "notification" << "notify");
addIcon(0xf0c3, QStringList() << "flask" << "science" << "beaker" << "experimental" << "labs");
addIcon(0xf16e, QStringList() << "flickr");
addIcon(0xf417, QStringList() << "fly");
addIcon(0xf07b, QStringList() << "folder");
addIcon(0xf07c, QStringList() << "folder open");
addIcon(0xf031, QStringList() << "font" << "text");
addIcon(0xf2b4, QStringList() << "font awesome" << "meanpath");
addIcon(0xf35c, QStringList() << "alternate font awesome");
addIcon(0xf425, QStringList() << "font awesome flag");
addIcon(0xf280, QStringList() << "fonticons");
addIcon(0xf3a2, QStringList() << "fonticons fi");
addIcon(0xf286, QStringList() << "fort awesome");
addIcon(0xf3a3, QStringList() << "alternate fort awesome");
addIcon(0xf211, QStringList() << "forumbee");
addIcon(0xf04e, QStringList() << "forward" << "forward" << "next");
addIcon(0xf180, QStringList() << "foursquare");
addIcon(0xf2c5, QStringList() << "free code camp");
addIcon(0xf3a4, QStringList() << "freebsd");
addIcon(0xf119, QStringList() << "frown" << "face" << "emoticon" << "sad" << "disapprove" << "rating");
addIcon(0xf1e3, QStringList() << "futbol");
addIcon(0xf11b, QStringList() << "gamepad" << "controller");
addIcon(0xf0e3, QStringList() << "gavel" << "judge" << "lawyer" << "opinion");
addIcon(0xf3a5, QStringList() << "gem" << "diamond");
addIcon(0xf22d, QStringList() << "genderless");
addIcon(0xf265, QStringList() << "get pocket");
addIcon(0xf260, QStringList() << "gg currency");
addIcon(0xf261, QStringList() << "gg currency circle");
addIcon(0xf06b, QStringList() << "gift" << "present");
addIcon(0xf1d3, QStringList() << "git");
addIcon(0xf1d2, QStringList() << "git square");
addIcon(0xf09b, QStringList() << "github" << "octocat");
addIcon(0xf113, QStringList() << "alternate github" << "octocat");
addIcon(0xf092, QStringList() << "github square" << "octocat");
addIcon(0xf3a6, QStringList() << "gitkraken");
addIcon(0xf296, QStringList() << "gitlab" << "Axosoft");
addIcon(0xf426, QStringList() << "gitter");
addIcon(0xf000, QStringList() << "martini glass" << "martini" << "drink" << "bar" << "alcohol" << "liquor" << "glass");
addIcon(0xf2a5, QStringList() << "glide");
addIcon(0xf2a6, QStringList() << "glide g");
addIcon(0xf0ac, QStringList() << "globe" << "world" << "planet" << "map" << "place" << "travel" << "earth" << "global" << "translate" << "all" << "language" << "localize" << "location" << "coordinates" << "country");
addIcon(0xf3a7, QStringList() << "gofore");
addIcon(0xf3a8, QStringList() << "goodreads");
addIcon(0xf3a9, QStringList() << "goodreads g");
addIcon(0xf1a0, QStringList() << "google logo");
addIcon(0xf3aa, QStringList() << "google drive");
addIcon(0xf3ab, QStringList() << "google play");
addIcon(0xf2b3, QStringList() << "google plus" << "google-plus-circle" << "google-plus-official");
addIcon(0xf0d5, QStringList() << "google plus g" << "social network" << "google-plus");
addIcon(0xf0d4, QStringList() << "google plus square" << "social network");
addIcon(0xf1ee, QStringList() << "google wallet");
addIcon(0xf19d, QStringList() << "graduation cap" << "learning" << "school" << "student");
addIcon(0xf184, QStringList() << "gratipay (gittip)" << "heart" << "like" << "favorite" << "love");
addIcon(0xf2d6, QStringList() << "grav");
addIcon(0xf3ac, QStringList() << "gripfire, inc.");
addIcon(0xf3ad, QStringList() << "grunt");
addIcon(0xf3ae, QStringList() << "gulp");
addIcon(0xf0fd, QStringList() << "h square" << "hospital" << "hotel");
addIcon(0xf1d4, QStringList() << "hacker news");
addIcon(0xf3af, QStringList() << "hacker news square");
addIcon(0xf258, QStringList() << "lizard (hand)");
addIcon(0xf256, QStringList() << "paper (hand)" << "stop");
addIcon(0xf25b, QStringList() << "peace (hand)");
addIcon(0xf0a7, QStringList() << "hand pointing down" << "point" << "finger" << "hand-o-down");
addIcon(0xf0a5, QStringList() << "hand pointing left" << "point" << "left" << "previous" << "back" << "finger" << "hand-o-left");
addIcon(0xf0a4, QStringList() << "hand pointing right" << "point" << "right" << "next" << "forward" << "finger" << "hand-o-right");
addIcon(0xf0a6, QStringList() << "hand pointing up" << "point" << "finger" << "hand-o-up");
addIcon(0xf25a, QStringList() << "pointer (hand)");
addIcon(0xf255, QStringList() << "rock (hand)");
addIcon(0xf257, QStringList() << "scissors (hand)");
addIcon(0xf259, QStringList() << "spock (hand)");
addIcon(0xf2b5, QStringList() << "handshake");
addIcon(0xf292, QStringList() << "hashtag");
addIcon(0xf0a0, QStringList() << "hdd" << "harddrive" << "hard drive" << "storage" << "save");
addIcon(0xf1dc, QStringList() << "heading" << "header" << "header");
addIcon(0xf025, QStringList() << "headphones" << "sound" << "listen" << "music" << "audio");
addIcon(0xf004, QStringList() << "heart" << "love" << "like" << "favorite");
addIcon(0xf21e, QStringList() << "heartbeat" << "ekg");
addIcon(0xf3b0, QStringList() << "hireahelper");
addIcon(0xf1da, QStringList() << "history");
addIcon(0xf015, QStringList() << "home" << "main" << "house");
addIcon(0xf427, QStringList() << "hooli");
addIcon(0xf0f8, QStringList() << "hospital" << "building");
addIcon(0xf3b1, QStringList() << "hotjar");
addIcon(0xf254, QStringList() << "hourglass");
addIcon(0xf253, QStringList() << "hourglass end");
addIcon(0xf252, QStringList() << "hourglass half");
addIcon(0xf251, QStringList() << "hourglass start");
addIcon(0xf27c, QStringList() << "houzz");
addIcon(0xf13b, QStringList() << "html 5 logo");
addIcon(0xf3b2, QStringList() << "hubspot");
addIcon(0xf246, QStringList() << "i beam cursor");
addIcon(0xf2c1, QStringList() << "identification badge");
addIcon(0xf2c2, QStringList() << "identification card");
addIcon(0xf03e, QStringList() << "image" << "photo" << "album" << "picture" << "picture");
addIcon(0xf302, QStringList() << "images" << "photo" << "album" << "picture");
addIcon(0xf2d8, QStringList() << "imdb");
addIcon(0xf01c, QStringList() << "inbox");
addIcon(0xf03c, QStringList() << "indent");
addIcon(0xf275, QStringList() << "industry" << "factory");
addIcon(0xf129, QStringList() << "info" << "help" << "information" << "more" << "details");
addIcon(0xf05a, QStringList() << "info circle" << "help" << "information" << "more" << "details");
addIcon(0xf16d, QStringList() << "instagram");
addIcon(0xf26b, QStringList() << "internet-explorer" << "browser" << "ie");
addIcon(0xf208, QStringList() << "ioxhost");
addIcon(0xf033, QStringList() << "italic" << "italics");
addIcon(0xf3b4, QStringList() << "itunes");
addIcon(0xf3b5, QStringList() << "itunes note");
addIcon(0xf3b6, QStringList() << "jenkis");
addIcon(0xf3b7, QStringList() << "joget");
addIcon(0xf1aa, QStringList() << "joomla logo");
addIcon(0xf3b8, QStringList() << "javascript (js)");
addIcon(0xf3b9, QStringList() << "javascript (js) square");
addIcon(0xf1cc, QStringList() << "jsfiddle");
addIcon(0xf084, QStringList() << "key" << "unlock" << "password");
addIcon(0xf11c, QStringList() << "keyboard" << "type" << "input");
addIcon(0xf3ba, QStringList() << "keycdn");
addIcon(0xf3bb, QStringList() << "kickstarter");
addIcon(0xf3bc, QStringList() << "kickstarter k");
addIcon(0xf42f, QStringList() << "korvue");
addIcon(0xf1ab, QStringList() << "language");
addIcon(0xf109, QStringList() << "laptop" << "demo" << "computer" << "device");
addIcon(0xf3bd, QStringList() << "laravel");
addIcon(0xf202, QStringList() << "last.fm");
addIcon(0xf203, QStringList() << "last.fm square");
addIcon(0xf06c, QStringList() << "leaf" << "eco" << "nature" << "plant");
addIcon(0xf212, QStringList() << "leanpub");
addIcon(0xf094, QStringList() << "lemon" << "food");
addIcon(0xf41d, QStringList() << "less");
addIcon(0xf3be, QStringList() << "level down-alt" << "level-down");
addIcon(0xf3bf, QStringList() << "level up-alt" << "level-up");
addIcon(0xf1cd, QStringList() << "life ring" << "support");
addIcon(0xf0eb, QStringList() << "lightbulb" << "idea" << "inspiration");
addIcon(0xf3c0, QStringList() << "line");
addIcon(0xf0c1, QStringList() << "link" << "chain");
addIcon(0xf08c, QStringList() << "linkedin" << "linkedin-square");
addIcon(0xf0e1, QStringList() << "linkedin in" << "linkedin");
addIcon(0xf2b8, QStringList() << "linode");
addIcon(0xf17c, QStringList() << "linux" << "tux");
addIcon(0xf195, QStringList() << "turkish lira sign" << "try" << "turkish" << "try");
addIcon(0xf03a, QStringList() << "list" << "ul" << "ol" << "checklist" << "finished" << "completed" << "done" << "todo");
addIcon(0xf022, QStringList() << "list-alt" << "ul" << "ol" << "checklist" << "finished" << "completed" << "done" << "todo");
addIcon(0xf0cb, QStringList() << "list-ol" << "ul" << "ol" << "checklist" << "list" << "todo" << "list" << "numbers");
addIcon(0xf0ca, QStringList() << "list-ul" << "ul" << "ol" << "checklist" << "todo" << "list");
addIcon(0xf124, QStringList() << "location-arrow" << "map" << "coordinates" << "location" << "address" << "place" << "where");
addIcon(0xf023, QStringList() << "lock" << "protect" << "admin" << "security");
addIcon(0xf3c1, QStringList() << "lock open" << "protect" << "admin" << "password" << "lock" << "open");
addIcon(0xf309, QStringList() << "alternate long arrow down" << "long-arrow-down");
addIcon(0xf30a, QStringList() << "alternate long arrow left" << "previous" << "back" << "long-arrow-left");
addIcon(0xf30b, QStringList() << "alternate long arrow right" << "long-arrow-right");
addIcon(0xf30c, QStringList() << "alternate long arrow up" << "long-arrow-up");
addIcon(0xf2a8, QStringList() << "low vision");
addIcon(0xf3c3, QStringList() << "lyft");
addIcon(0xf3c4, QStringList() << "magento");
addIcon(0xf0d0, QStringList() << "magic" << "wizard" << "automatic" << "autocomplete");
addIcon(0xf076, QStringList() << "magnet");
addIcon(0xf183, QStringList() << "male" << "man" << "user" << "person" << "profile");
addIcon(0xf279, QStringList() << "map");
addIcon(0xf041, QStringList() << "map-marker" << "map" << "pin" << "location" << "coordinates" << "localize" << "address" << "travel" << "where" << "place");
addIcon(0xf3c5, QStringList() << "map marker-alt" << "map-marker");
addIcon(0xf276, QStringList() << "map pin");
addIcon(0xf277, QStringList() << "map signs");
addIcon(0xf222, QStringList() << "mars" << "male");
addIcon(0xf227, QStringList() << "mars double");
addIcon(0xf229, QStringList() << "mars stroke");
addIcon(0xf22b, QStringList() << "mars stroke horizontal");
addIcon(0xf22a, QStringList() << "mars stroke vertical");
addIcon(0xf136, QStringList() << "maxcdn");
addIcon(0xf3c6, QStringList() << "medapps");
addIcon(0xf23a, QStringList() << "medium");
addIcon(0xf3c7, QStringList() << "medium m");
addIcon(0xf0fa, QStringList() << "medkit" << "first aid" << "firstaid" << "help" << "support" << "health");
addIcon(0xf3c8, QStringList() << "mrt");
addIcon(0xf2e0, QStringList() << "meetup");
addIcon(0xf11a, QStringList() << "meh" << "face" << "emoticon" << "rating" << "neutral");
addIcon(0xf223, QStringList() << "mercury" << "transgender");
addIcon(0xf2db, QStringList() << "microchip");
addIcon(0xf130, QStringList() << "microphone" << "record" << "voice" << "sound");
addIcon(0xf131, QStringList() << "microphone slash" << "record" << "voice" << "sound" << "mute");
addIcon(0xf3ca, QStringList() << "microsoft");
addIcon(0xf068, QStringList() << "minus" << "hide" << "minify" << "delete" << "remove" << "trash" << "hide" << "collapse");
addIcon(0xf056, QStringList() << "minus circle" << "delete" << "remove" << "trash" << "hide");
addIcon(0xf146, QStringList() << "minus square" << "hide" << "minify" << "delete" << "remove" << "trash" << "hide" << "collapse");
addIcon(0xf3cb, QStringList() << "mix");
addIcon(0xf289, QStringList() << "mixcloud");
addIcon(0xf3cc, QStringList() << "mizuni");
addIcon(0xf10b, QStringList() << "mobile phone" << "cell phone" << "cellphone" << "text" << "call" << "iphone" << "number" << "telephone");
addIcon(0xf3cd, QStringList() << "alternate mobile" << "mobile");
addIcon(0xf285, QStringList() << "modx");
addIcon(0xf3d0, QStringList() << "monero");
addIcon(0xf3d1, QStringList() << "money bill-alt" << "money");
addIcon(0xf186, QStringList() << "moon" << "night" << "darker" << "contrast");
addIcon(0xf21c, QStringList() << "motorcycle" << "vehicle" << "bike");
addIcon(0xf245, QStringList() << "mouse pointer");
addIcon(0xf001, QStringList() << "music" << "note" << "sound");
addIcon(0xf3d2, QStringList() << "napster");
addIcon(0xf22c, QStringList() << "neuter");
addIcon(0xf1ea, QStringList() << "newspaper" << "press");
addIcon(0xf418, QStringList() << "nintendo switch");
addIcon(0xf419, QStringList() << "node.js");
addIcon(0xf3d3, QStringList() << "node.js js");
addIcon(0xf3d4, QStringList() << "npm");
addIcon(0xf3d5, QStringList() << "ns8");
addIcon(0xf3d6, QStringList() << "nutritionix");
addIcon(0xf247, QStringList() << "object group");
addIcon(0xf248, QStringList() << "object ungroup");
addIcon(0xf263, QStringList() << "odnoklassniki");
addIcon(0xf264, QStringList() << "odnoklassniki square");
addIcon(0xf23d, QStringList() << "opencart");
addIcon(0xf19b, QStringList() << "openid");
addIcon(0xf26a, QStringList() << "opera");
addIcon(0xf23c, QStringList() << "optin monster");
addIcon(0xf41a, QStringList() << "open source initiative");
addIcon(0xf03b, QStringList() << "outdent");
addIcon(0xf3d7, QStringList() << "page4 corporation");
addIcon(0xf18c, QStringList() << "pagelines" << "leaf" << "leaves" << "tree" << "plant" << "eco" << "nature");
addIcon(0xf1fc, QStringList() << "paint brush");
addIcon(0xf3d8, QStringList() << "palfed");
addIcon(0xf1d8, QStringList() << "paper plane");
addIcon(0xf0c6, QStringList() << "paperclip" << "attachment");
addIcon(0xf1dd, QStringList() << "paragraph");
addIcon(0xf0ea, QStringList() << "paste" << "copy" << "clipboard");
addIcon(0xf3d9, QStringList() << "patreon");
addIcon(0xf04c, QStringList() << "pause" << "wait");
addIcon(0xf28b, QStringList() << "pause circle");
addIcon(0xf1b0, QStringList() << "paw" << "pet");
addIcon(0xf1ed, QStringList() << "paypal");
addIcon(0xf14b, QStringList() << "pen square" << "write" << "edit" << "update" << "pencil-square");
addIcon(0xf303, QStringList() << "alternate pencil" << "write" << "edit" << "update" << "pencil");
addIcon(0xf295, QStringList() << "percent");
addIcon(0xf3da, QStringList() << "periscope");
addIcon(0xf3db, QStringList() << "phabricator");
addIcon(0xf3dc, QStringList() << "phoenix framework");
addIcon(0xf095, QStringList() << "phone" << "call" << "voice" << "number" << "support" << "earphone" << "telephone");
addIcon(0xf098, QStringList() << "phone square" << "call" << "voice" << "number" << "support" << "telephone");
addIcon(0xf2a0, QStringList() << "phone volume" << "telephone" << "volume-control-phone");
addIcon(0xf2ae, QStringList() << "pied piper logo");
addIcon(0xf1a8, QStringList() << "alternate pied piper logo");
addIcon(0xf1a7, QStringList() << "pied piper pp logo (old)");
addIcon(0xf0d2, QStringList() << "pinterest");
addIcon(0xf231, QStringList() << "pinterest p");
addIcon(0xf0d3, QStringList() << "pinterest square");
addIcon(0xf072, QStringList() << "plane" << "travel" << "trip" << "location" << "destination" << "airplane" << "fly" << "mode");
addIcon(0xf04b, QStringList() << "play" << "start" << "playing" << "music" << "sound");
addIcon(0xf144, QStringList() << "play circle" << "start" << "playing");
addIcon(0xf3df, QStringList() << "playstation");
addIcon(0xf1e6, QStringList() << "plug" << "power" << "connect");
addIcon(0xf067, QStringList() << "plus" << "add" << "new" << "create" << "expand");
addIcon(0xf055, QStringList() << "plus circle" << "add" << "new" << "create" << "expand");
addIcon(0xf0fe, QStringList() << "plus square" << "add" << "new" << "create" << "expand");
addIcon(0xf2ce, QStringList() << "podcast");
addIcon(0xf154, QStringList() << "pound sign" << "gbp" << "gbp");
addIcon(0xf011, QStringList() << "power off" << "on");
addIcon(0xf02f, QStringList() << "print");
addIcon(0xf288, QStringList() << "product hunt");
addIcon(0xf3e1, QStringList() << "pushed");
addIcon(0xf12e, QStringList() << "puzzle piece" << "addon" << "add-on" << "section");
addIcon(0xf3e2, QStringList() << "python");
addIcon(0xf1d6, QStringList() << "qq");
addIcon(0xf029, QStringList() << "qrcode" << "scan");
addIcon(0xf128, QStringList() << "question" << "help" << "information" << "unknown" << "support");
addIcon(0xf059, QStringList() << "question circle" << "help" << "information" << "unknown" << "support");
addIcon(0xf2c4, QStringList() << "quora");
addIcon(0xf10d, QStringList() << "quote-left");
addIcon(0xf10e, QStringList() << "quote-right");
addIcon(0xf074, QStringList() << "random" << "sort" << "shuffle");
addIcon(0xf2d9, QStringList() << "ravelry");
addIcon(0xf41b, QStringList() << "react");
addIcon(0xf1d0, QStringList() << "rebel alliance");
addIcon(0xf1b8, QStringList() << "recycle");
addIcon(0xf3e3, QStringList() << "red river");
addIcon(0xf1a1, QStringList() << "reddit logo");
addIcon(0xf281, QStringList() << "reddit alien");
addIcon(0xf1a2, QStringList() << "reddit square");
addIcon(0xf01e, QStringList() << "redo" << "forward" << "repeat" << "repeat");
addIcon(0xf2f9, QStringList() << "alternate redo" << "forward" << "repeat");
addIcon(0xf25d, QStringList() << "registered trademark");
addIcon(0xf3e4, QStringList() << "rendact");
addIcon(0xf18b, QStringList() << "renren");
addIcon(0xf3e5, QStringList() << "reply");
addIcon(0xf122, QStringList() << "reply-all");
addIcon(0xf3e6, QStringList() << "replyd");
addIcon(0xf3e7, QStringList() << "resolving");
addIcon(0xf079, QStringList() << "retweet" << "refresh" << "reload" << "share");
addIcon(0xf018, QStringList() << "road" << "street");
addIcon(0xf135, QStringList() << "rocket" << "app");
addIcon(0xf3e8, QStringList() << "rocket.chat");
addIcon(0xf3e9, QStringList() << "rockrms");
addIcon(0xf09e, QStringList() << "rss" << "blog");
addIcon(0xf143, QStringList() << "rss square" << "feed" << "blog");
addIcon(0xf158, QStringList() << "ruble sign" << "rub" << "rub");
addIcon(0xf156, QStringList() << "indian rupee sign" << "indian" << "inr");
addIcon(0xf267, QStringList() << "safari" << "browser");
addIcon(0xf41e, QStringList() << "sass");
addIcon(0xf0c7, QStringList() << "save" << "floppy" << "floppy-o");
addIcon(0xf3ea, QStringList() << "schlix");
addIcon(0xf28a, QStringList() << "scribd");
addIcon(0xf002, QStringList() << "search" << "magnify" << "zoom" << "enlarge" << "bigger");
addIcon(0xf010, QStringList() << "search minus" << "magnify" << "minify" << "zoom" << "smaller");
addIcon(0xf00e, QStringList() << "search plus" << "magnify" << "zoom" << "enlarge" << "bigger");
addIcon(0xf3eb, QStringList() << "searchengin");
addIcon(0xf2da, QStringList() << "sellcast" << "eercast");
addIcon(0xf213, QStringList() << "sellsy");
addIcon(0xf233, QStringList() << "server");
addIcon(0xf3ec, QStringList() << "servicestack");
addIcon(0xf064, QStringList() << "share");
addIcon(0xf1e0, QStringList() << "alternate share");
addIcon(0xf1e1, QStringList() << "alternate share square");
addIcon(0xf14d, QStringList() << "share square" << "social" << "send");
addIcon(0xf20b, QStringList() << "shekel sign" << "ils" << "ils");
addIcon(0xf3ed, QStringList() << "alternate shield" << "shield");
addIcon(0xf21a, QStringList() << "ship" << "boat" << "sea");
addIcon(0xf214, QStringList() << "shirts in bulk");
addIcon(0xf290, QStringList() << "shopping bag");
addIcon(0xf291, QStringList() << "shopping basket");
addIcon(0xf07a, QStringList() << "shopping-cart" << "checkout" << "buy" << "purchase" << "payment");
addIcon(0xf2cc, QStringList() << "shower");
addIcon(0xf2f6, QStringList() << "alernate sign in" << "enter" << "join" << "log in" << "login" << "sign up" << "sign in" << "signin" << "signup" << "arrow" << "sign-in");
addIcon(0xf2a7, QStringList() << "sign language");
addIcon(0xf2f5, QStringList() << "alernate sign out" << "log out" << "logout" << "leave" << "exit" << "arrow" << "sign-out");
addIcon(0xf012, QStringList() << "signal" << "graph" << "bars");
addIcon(0xf215, QStringList() << "simplybuilt");
addIcon(0xf3ee, QStringList() << "sistrix");
addIcon(0xf0e8, QStringList() << "sitemap" << "directory" << "hierarchy" << "organization");
addIcon(0xf216, QStringList() << "skyatlas");
addIcon(0xf17e, QStringList() << "skype");
addIcon(0xf198, QStringList() << "slack logo" << "hashtag" << "anchor" << "hash");
addIcon(0xf3ef, QStringList() << "slack hashtag" << "hashtag" << "anchor" << "hash");
addIcon(0xf1de, QStringList() << "horizontal sliders" << "settings" << "sliders");
addIcon(0xf1e7, QStringList() << "slideshare");
addIcon(0xf118, QStringList() << "smile" << "face" << "emoticon" << "happy" << "approve" << "satisfied" << "rating");
addIcon(0xf2ab, QStringList() << "snapchat");
addIcon(0xf2ac, QStringList() << "snapchat ghost");
addIcon(0xf2ad, QStringList() << "snapchat square");
addIcon(0xf2dc, QStringList() << "snowflake");
addIcon(0xf0dc, QStringList() << "sort" << "order");
addIcon(0xf15d, QStringList() << "sort alpha down" << "sort-alpha-asc");
addIcon(0xf15e, QStringList() << "sort alpha up" << "sort-alpha-desc");
addIcon(0xf160, QStringList() << "sort amount down" << "sort-amount-asc");
addIcon(0xf161, QStringList() << "sort amount up" << "sort-amount-desc");
addIcon(0xf0dd, QStringList() << "sort down (descending)" << "arrow" << "descending" << "sort-desc");
addIcon(0xf162, QStringList() << "sort numeric down" << "numbers" << "sort-numeric-asc");
addIcon(0xf163, QStringList() << "sort numeric up" << "numbers" << "sort-numeric-desc");
addIcon(0xf0de, QStringList() << "sort up (ascending)" << "arrow" << "ascending" << "sort-asc");
addIcon(0xf1be, QStringList() << "soundcloud");
addIcon(0xf197, QStringList() << "space shuttle");
addIcon(0xf3f3, QStringList() << "speakap");
addIcon(0xf110, QStringList() << "spinner" << "loading" << "progress");
addIcon(0xf1bc, QStringList() << "spotify");
addIcon(0xf0c8, QStringList() << "square" << "block" << "box");
addIcon(0xf18d, QStringList() << "stack exchange");
addIcon(0xf16c, QStringList() << "stack overflow");
addIcon(0xf005, QStringList() << "star" << "award" << "achievement" << "night" << "rating" << "score" << "favorite");
addIcon(0xf089, QStringList() << "star-half" << "award" << "achievement" << "rating" << "score" << "star-half-empty" << "star-half-full");
addIcon(0xf3f5, QStringList() << "staylinked");
addIcon(0xf1b6, QStringList() << "steam");
addIcon(0xf1b7, QStringList() << "steam square");
addIcon(0xf3f6, QStringList() << "steam symbol");
addIcon(0xf048, QStringList() << "step-backward" << "rewind" << "previous" << "beginning" << "start" << "first");
addIcon(0xf051, QStringList() << "step-forward" << "next" << "end" << "last");
addIcon(0xf0f1, QStringList() << "stethoscope");
addIcon(0xf3f7, QStringList() << "sticker mule");
addIcon(0xf249, QStringList() << "sticky note");
addIcon(0xf04d, QStringList() << "stop" << "block" << "box" << "square");
addIcon(0xf28d, QStringList() << "stop circle");
addIcon(0xf2f2, QStringList() << "stopwatch" << "time");
addIcon(0xf428, QStringList() << "strava");
addIcon(0xf21d, QStringList() << "street view" << "map");
addIcon(0xf0cc, QStringList() << "strikethrough");
addIcon(0xf429, QStringList() << "stripe");
addIcon(0xf42a, QStringList() << "stripe s");
addIcon(0xf3f8, QStringList() << "studio vinari");
addIcon(0xf1a4, QStringList() << "stumbleupon logo");
addIcon(0xf1a3, QStringList() << "stumbleupon circle");
addIcon(0xf12c, QStringList() << "subscript");
addIcon(0xf239, QStringList() << "subway");
addIcon(0xf0f2, QStringList() << "suitcase" << "trip" << "luggage" << "travel" << "move" << "baggage");
addIcon(0xf185, QStringList() << "sun" << "weather" << "contrast" << "lighter" << "brighten" << "day");
addIcon(0xf2dd, QStringList() << "superpowers");
addIcon(0xf12b, QStringList() << "superscript" << "exponential");
addIcon(0xf3f9, QStringList() << "supple");
addIcon(0xf021, QStringList() << "sync" << "reload" << "refresh" << "refresh");
addIcon(0xf2f1, QStringList() << "alternate sync" << "reload" << "refresh");
addIcon(0xf0ce, QStringList() << "table" << "data" << "excel" << "spreadsheet");
addIcon(0xf10a, QStringList() << "tablet" << "ipad" << "device");
addIcon(0xf3fa, QStringList() << "alternate tablet" << "tablet");
addIcon(0xf3fd, QStringList() << "alternate tachometer" << "tachometer");
addIcon(0xf02b, QStringList() << "tag" << "label");
addIcon(0xf02c, QStringList() << "tags" << "labels");
addIcon(0xf0ae, QStringList() << "tasks" << "progress" << "loading" << "downloading" << "downloads" << "settings");
addIcon(0xf1ba, QStringList() << "taxi" << "vehicle");
addIcon(0xf2c6, QStringList() << "telegram");
addIcon(0xf3fe, QStringList() << "telegram plane");
addIcon(0xf1d5, QStringList() << "tencent weibo");
addIcon(0xf120, QStringList() << "terminal" << "command" << "prompt" << "code");
addIcon(0xf034, QStringList() << "text-height");
addIcon(0xf035, QStringList() << "text-width");
addIcon(0xf00a, QStringList() << "th" << "blocks" << "squares" << "boxes" << "grid");
addIcon(0xf009, QStringList() << "th-large" << "blocks" << "squares" << "boxes" << "grid");
addIcon(0xf00b, QStringList() << "th-list" << "ul" << "ol" << "checklist" << "finished" << "completed" << "done" << "todo");
addIcon(0xf2b2, QStringList() << "themeisle");
addIcon(0xf2cb, QStringList() << "thermometer empty");
addIcon(0xf2c7, QStringList() << "thermometer full");
addIcon(0xf2c9, QStringList() << "thermometer 1/2 full");
addIcon(0xf2ca, QStringList() << "thermometer 1/4 full");
addIcon(0xf2c8, QStringList() << "thermometer 3/4 full");
addIcon(0xf165, QStringList() << "thumbs-down" << "dislike" << "disapprove" << "disagree" << "hand" << "thumbs-o-down");
addIcon(0xf164, QStringList() << "thumbs-up" << "like" << "favorite" << "approve" << "agree" << "hand" << "thumbs-o-up");
addIcon(0xf08d, QStringList() << "thumbtack" << "marker" << "pin" << "location" << "coordinates" << "thumb-tack");
addIcon(0xf3ff, QStringList() << "alernate ticket" << "ticket");
addIcon(0xf00d, QStringList() << "times" << "close" << "exit" << "x" << "cross");
addIcon(0xf057, QStringList() << "times circle" << "close" << "exit" << "x");
addIcon(0xf043, QStringList() << "tint" << "raindrop" << "waterdrop" << "drop" << "droplet");
addIcon(0xf204, QStringList() << "toggle off");
addIcon(0xf205, QStringList() << "toggle on");
addIcon(0xf25c, QStringList() << "trademark");
addIcon(0xf238, QStringList() << "train");
addIcon(0xf224, QStringList() << "transgender" << "intersex");
addIcon(0xf225, QStringList() << "alternate transgender");
addIcon(0xf1f8, QStringList() << "trash" << "garbage" << "delete" << "remove" << "hide");
addIcon(0xf2ed, QStringList() << "alternate trash" << "garbage" << "delete" << "remove" << "hide" << "trash" << "trash-o");
addIcon(0xf1bb, QStringList() << "tree");
addIcon(0xf181, QStringList() << "trello");
addIcon(0xf262, QStringList() << "tripadvisor");
addIcon(0xf091, QStringList() << "trophy" << "award" << "achievement" << "cup" << "winner" << "game");
addIcon(0xf0d1, QStringList() << "truck" << "shipping");
addIcon(0xf1e4, QStringList() << "tty");
addIcon(0xf173, QStringList() << "tumblr");
addIcon(0xf174, QStringList() << "tumblr square");
addIcon(0xf26c, QStringList() << "television" << "display" << "computer" << "monitor" << "television");
addIcon(0xf1e8, QStringList() << "twitch");
addIcon(0xf099, QStringList() << "twitter" << "tweet" << "social network");
addIcon(0xf081, QStringList() << "twitter square" << "tweet" << "social network");
addIcon(0xf42b, QStringList() << "typo3");
addIcon(0xf402, QStringList() << "uber");
addIcon(0xf403, QStringList() << "uikit");
addIcon(0xf0e9, QStringList() << "umbrella");
addIcon(0xf0cd, QStringList() << "underline");
addIcon(0xf0e2, QStringList() << "undo" << "back");
addIcon(0xf2ea, QStringList() << "alternate undo" << "back");
addIcon(0xf404, QStringList() << "uniregistry");
addIcon(0xf29a, QStringList() << "universal access");
addIcon(0xf19c, QStringList() << "university");
addIcon(0xf127, QStringList() << "unlink" << "remove" << "chain" << "chain-broken");
addIcon(0xf09c, QStringList() << "unlock" << "protect" << "admin" << "password" << "lock");
addIcon(0xf13e, QStringList() << "alternate unlock" << "protect" << "admin" << "password" << "lock");
addIcon(0xf405, QStringList() << "untappd");
addIcon(0xf093, QStringList() << "upload" << "import");
addIcon(0xf287, QStringList() << "usb");
addIcon(0xf007, QStringList() << "user" << "person" << "man" << "head" << "profile");
addIcon(0xf2bd, QStringList() << "user circle");
addIcon(0xf0f0, QStringList() << "user-md" << "doctor" << "profile" << "medical" << "nurse");
addIcon(0xf234, QStringList() << "add user" << "sign up" << "signup");
addIcon(0xf21b, QStringList() << "user secret" << "whisper" << "spy" << "incognito" << "privacy");
addIcon(0xf235, QStringList() << "remove user");
addIcon(0xf0c0, QStringList() << "users" << "people" << "profiles" << "persons");
addIcon(0xf407, QStringList() << "us-sunnah foundation");
addIcon(0xf2e5, QStringList() << "utensil spoon" << "spoon");
addIcon(0xf2e7, QStringList() << "utensils" << "food" << "restaurant" << "spoon" << "knife" << "dinner" << "eat" << "cutlery");
addIcon(0xf408, QStringList() << "vaadin");
addIcon(0xf221, QStringList() << "venus" << "female");
addIcon(0xf226, QStringList() << "venus double");
addIcon(0xf228, QStringList() << "venus mars");
addIcon(0xf237, QStringList() << "viacoin");
addIcon(0xf2a9, QStringList() << "viadeo");
addIcon(0xf2aa, QStringList() << "viadeo square");
addIcon(0xf409, QStringList() << "viber");
addIcon(0xf03d, QStringList() << "video" << "film" << "movie" << "record" << "camera" << "video-camera");
addIcon(0xf40a, QStringList() << "vimeo");
addIcon(0xf194, QStringList() << "vimeo square");
addIcon(0xf27d, QStringList() << "vimeo" << "vimeo");
addIcon(0xf1ca, QStringList() << "vine");
addIcon(0xf189, QStringList() << "vk");
addIcon(0xf40b, QStringList() << "vnv");
addIcon(0xf027, QStringList() << "volume-down" << "audio" << "lower" << "quieter" << "sound" << "music");
addIcon(0xf026, QStringList() << "volume-off" << "audio" << "mute" << "sound" << "music");
addIcon(0xf028, QStringList() << "volume-up" << "audio" << "higher" << "louder" << "sound" << "music");
addIcon(0xf41f, QStringList() << "vue.js");
addIcon(0xf18a, QStringList() << "weibo");
addIcon(0xf1d7, QStringList() << "weixin (wechat)");
addIcon(0xf232, QStringList() << "what's app");
addIcon(0xf40c, QStringList() << "what's app square");
addIcon(0xf193, QStringList() << "wheelchair" << "handicap" << "person");
addIcon(0xf40d, QStringList() << "whmcs");
addIcon(0xf1eb, QStringList() << "wifi");
addIcon(0xf266, QStringList() << "wikipedia w");
addIcon(0xf410, QStringList() << "window close");
addIcon(0xf2d0, QStringList() << "window maximize");
addIcon(0xf2d1, QStringList() << "window minimize");
addIcon(0xf2d2, QStringList() << "window restore");
addIcon(0xf17a, QStringList() << "windows" << "microsoft");
addIcon(0xf159, QStringList() << "won sign" << "krw" << "krw");
addIcon(0xf19a, QStringList() << "wordpress logo");
addIcon(0xf411, QStringList() << "wordpress simple");
addIcon(0xf297, QStringList() << "wpbeginner");
addIcon(0xf2de, QStringList() << "wpexplorer");
addIcon(0xf298, QStringList() << "wpforms");
addIcon(0xf0ad, QStringList() << "wrench" << "settings" << "fix" << "update" << "spanner");
addIcon(0xf412, QStringList() << "xbox");
addIcon(0xf168, QStringList() << "xing");
addIcon(0xf169, QStringList() << "xing square");
addIcon(0xf23b, QStringList() << "y combinator");
addIcon(0xf19e, QStringList() << "yahoo logo");
addIcon(0xf413, QStringList() << "yandex");
addIcon(0xf414, QStringList() << "yandex international");
addIcon(0xf1e9, QStringList() << "yelp");
addIcon(0xf157, QStringList() << "yen sign" << "jpy" << "jpy");
addIcon(0xf2b1, QStringList() << "yoast");
addIcon(0xf167, QStringList() << "youtube" << "video" << "film" << "youtube-play" << "youtube-square");
